---
apiVersion: v1
kind: Namespace
metadata:
  name: passt-kubevirt-network-binding-plugin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: passt-kubevirt-network-binding-plugin
  namespace: passt-kubevirt-network-binding-plugin
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: passt-kubevirt-network-binding-plugin
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:passt-kubevirt-network-binding-plugin:passt-kubevirt-network-binding-plugin
volumes:
- "*"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: passt-kubevirt-network-binding-plugin
  namespace: passt-kubevirt-network-binding-plugin
  labels:
    tier: node
    app: passt-kubevirt-network-binding-plugin
spec:
  selector:
    matchLabels:
      name: passt-kubevirt-network-binding-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        name: passt-kubevirt-network-binding-plugin
        tier: node
        app: cni-plugins
      annotations:
        description: Deploys the passt CNI plugin accross the cluster
    spec:
      serviceAccountName: passt-kubevirt-network-binding-plugin
      priorityClassName: system-cluster-critical
      containers:
        - name: cni-plugins
          image: quay.io/phoracek/passt-kubevirt-binding-plugin-cni
          command:
            - /bin/bash
            - -ce
            - |
              cp --remove-destination /bin/passt /opt/cni/bin
              echo 'Entering sleep... (success)'
              sleep infinity
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /var/lib/cni/bin
